sudo: required
dist: trusty

before_install:
  - date
  - cat /proc/cpuinfo
  - cd ${HOME}
  # Install packges
  - sudo apt-get -qq -y install libgmp-dev haskell-platform cabal-install
  - gcc --version
  - cabal update
  - export PATH=${HOME}/.cabal/bin:${PATH}
  # Clone
  - git clone https://github.com/githwxi/ATS-Postiats.git
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git
  # Build ATS1
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.12
  - export ATSHOMERELOC=ATS-0.2.12
  - ${HOME}/ATS-Postiats/travis-ci/ats1_setup.sh 0.2.12
  - cd ${ATSHOME} && ./configure && make
  # Build ATS2
  - export PATSHOME=${HOME}/ATS-Postiats
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
  - export PATH=${PATH}:${PATSHOME}/bin
  - cd ${PATSHOME} && make -f codegen/Makefile_atslib && make -f Makefile_devl src_depend && make -f Makefile_devl all

script:
  - cd ${TRAVIS_BUILD_DIR}
  - make install
  - make all
  - cat example/complex/example.sats
  - make test

after_script:
  - date
