# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

matrix:
  include:
  - env: CABALVER=1.24 GHCVER=7.10.3
    addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,libgmp-dev,libgtk-3-dev], sources: [hvr-ghc]}}
  - env: CABALVER=head GHCVER=head
    addons: {apt: {packages: [cabal-install-head,ghc-head,libgmp-dev,libgtk-3-dev],  sources: [hvr-ghc]}}

before_install:
  - date
  - cat /proc/cpuinfo
  - unset CC
  - export PATH=${HOME}/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:${PATH}
  - cd ${HOME}
  # Clone
  - git clone https://github.com/githwxi/ATS-Postiats.git
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git
  # Build ATS1
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.12
  - export ATSHOMERELOC=ATS-0.2.12
  - ${HOME}/ATS-Postiats/travis-ci/ats1_setup.sh 0.2.12
  - cd ${ATSHOME} && ./configure && make
  # Build ATS2
  - export PATSHOME=${HOME}/ATS-Postiats
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
  - export PATH=${PATH}:${PATSHOME}/bin
  - cd ${PATSHOME} && make -f codegen/Makefile_atslib && make -f Makefile_devl src_depend && make -f Makefile_devl all
  - gcc --version
  - ghc --version
  - patsopt --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cabal update
  - make install
  - make test

after_script:
  - date
