sudo: required
dist: trusty

before_install:
  - date
  - sudo apt-get -qq -y install haskell-platform cabal-install
  - cabal update
  - export PATH=${HOME}/.cabal/bin:${PATH}

script:
  - cabal install
  - c2ats new example/complex/example.c

after_script:
  - date
