sudo: required
dist: trusty

before_install:
  - date
  - sudo apt-get -qq -y install haskell-platform cabal-install

script:
  - cabal update
  - cabal install
  - c2ats new example/complex/example.c

after_script:
  - date
